/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p03;

import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author BG-307
 */
public class Window03 extends javax.swing.JFrame {

    /**
     * Creates new form Window03
     */
    public Window03() {
        initComponents();
        jTabbedPane1.setSelectedIndex(2);
        txt數字1.requestFocus();
        btn檢核.setVisible(false);
        btn等於.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt使用者 = new javax.swing.JTextField();
        txt密碼 = new javax.swing.JTextField();
        btn檢核 = new javax.swing.JButton();
        lbl通過 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt分數 = new javax.swing.JTextField();
        lbl分數等級 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txt數字1 = new javax.swing.JTextField();
        txt數字2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        rdo加 = new javax.swing.JRadioButton();
        rdo減 = new javax.swing.JRadioButton();
        rdo乘 = new javax.swing.JRadioButton();
        rdo除 = new javax.swing.JRadioButton();
        btn等於 = new javax.swing.JButton();
        lbl答案 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jLabel1.setText("使用者");

        jLabel2.setText("密碼");

        txt使用者.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt使用者FocusGained(evt);
            }
        });
        txt使用者.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt使用者ActionPerformed(evt);
            }
        });

        txt密碼.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt密碼FocusGained(evt);
            }
        });
        txt密碼.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt密碼ActionPerformed(evt);
            }
        });

        btn檢核.setText("檢核");
        btn檢核.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn檢核ActionPerformed(evt);
            }
        });

        lbl通過.setBackground(new java.awt.Color(255, 255, 0));
        lbl通過.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt使用者)
                                    .addComponent(txt密碼, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)))
                            .addComponent(lbl通過, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(btn檢核)))
                .addContainerGap(287, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt使用者, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt密碼, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn檢核)
                .addGap(18, 18, 18)
                .addComponent(lbl通過, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("密碼檢核", jPanel1);

        jLabel3.setFont(new java.awt.Font("標楷體", 1, 24)); // NOI18N
        jLabel3.setText("分數");

        txt分數.setFont(new java.awt.Font("標楷體", 1, 24)); // NOI18N
        txt分數.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt分數ActionPerformed(evt);
            }
        });

        lbl分數等級.setBackground(new java.awt.Color(102, 255, 51));
        lbl分數等級.setFont(new java.awt.Font("標楷體", 1, 24)); // NOI18N
        lbl分數等級.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt分數, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(lbl分數等級, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(206, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt分數, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(lbl分數等級, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("分數等級", jPanel2);

        txt數字1.setFont(new java.awt.Font("標楷體", 1, 24)); // NOI18N
        txt數字1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt數字1ActionPerformed(evt);
            }
        });

        txt數字2.setFont(new java.awt.Font("標楷體", 1, 24)); // NOI18N

        jPanel4.setLayout(new java.awt.GridLayout(0, 1, 10, 10));

        buttonGroup1.add(rdo加);
        rdo加.setFont(new java.awt.Font("標楷體", 1, 24)); // NOI18N
        rdo加.setText("加");
        rdo加.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                加減乘除共用事件(evt);
            }
        });
        jPanel4.add(rdo加);

        buttonGroup1.add(rdo減);
        rdo減.setFont(new java.awt.Font("標楷體", 1, 24)); // NOI18N
        rdo減.setText("減");
        rdo減.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                加減乘除共用事件(evt);
            }
        });
        jPanel4.add(rdo減);

        buttonGroup1.add(rdo乘);
        rdo乘.setFont(new java.awt.Font("標楷體", 1, 24)); // NOI18N
        rdo乘.setText("乘");
        rdo乘.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                加減乘除共用事件(evt);
            }
        });
        jPanel4.add(rdo乘);

        buttonGroup1.add(rdo除);
        rdo除.setFont(new java.awt.Font("標楷體", 1, 24)); // NOI18N
        rdo除.setText("除");
        rdo除.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                加減乘除共用事件(evt);
            }
        });
        jPanel4.add(rdo除);

        btn等於.setFont(new java.awt.Font("標楷體", 1, 24)); // NOI18N
        btn等於.setText("等於");
        btn等於.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn等於ActionPerformed(evt);
            }
        });

        lbl答案.setBackground(new java.awt.Color(153, 255, 102));
        lbl答案.setFont(new java.awt.Font("標楷體", 1, 24)); // NOI18N
        lbl答案.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt數字2, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(txt數字1))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(btn等於)
                .addGap(18, 18, 18)
                .addComponent(lbl答案, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(txt數字1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt數字2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn等於)
                            .addComponent(lbl答案, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("四則運算", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn檢核ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn檢核ActionPerformed
        String userid, password;
        final String user = "sun2000", pass = "1234";

        userid = txt使用者.getText();
        password = txt密碼.getText();

        if (userid.equals(user) && password.equals(pass)) {
            lbl通過.setText("Pass");
        } else {
            lbl通過.setText("No Pass");
        }
    }//GEN-LAST:event_btn檢核ActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        txt使用者.requestFocus();
        txt分數.requestFocus();
        txt數字1.requestFocus();
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void txt使用者ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt使用者ActionPerformed
        if (txt使用者.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "使用者不可空白");
            return;
        }

        txt密碼.requestFocus();
    }//GEN-LAST:event_txt使用者ActionPerformed

    private void txt密碼ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt密碼ActionPerformed
        if (txt密碼.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "密碼不可空白");
            return;
        }

        btn檢核ActionPerformed(evt);
    }//GEN-LAST:event_txt密碼ActionPerformed

    private void txt使用者FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt使用者FocusGained
        txt使用者.selectAll();
    }//GEN-LAST:event_txt使用者FocusGained

    private void txt密碼FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt密碼FocusGained
        txt密碼.selectAll();
    }//GEN-LAST:event_txt密碼FocusGained

    private void txt分數ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt分數ActionPerformed
        int grade;
        grade = Integer.parseInt(txt分數.getText());

        if (grade > 100 || grade < 0) {
            lbl分數等級.setText("你的分數輸入錯誤");
            return;
        }
        switch (grade / 10) {
            case 10:
            case 9:
                lbl分數等級.setText("成績：優等");
                break;
            case 8:
                lbl分數等級.setText("成績：甲等");
                break;
            case 7:
                lbl分數等級.setText("成績：乙等");
                break;
            case 6:
                lbl分數等級.setText("成績：丙等");
                break;
            default:
                lbl分數等級.setText("成績：丁等");
        }
    }//GEN-LAST:event_txt分數ActionPerformed

    private void btn等於ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn等於ActionPerformed
        int x, y;
        int sum = 0;
        x = Integer.parseInt(txt數字1.getText());
        y = Integer.parseInt(txt數字2.getText());

        if (rdo加.isSelected()) {
            sum = 四則運算(x, y, Count.加);
        }
        if (rdo減.isSelected()) {
            sum = 四則運算(x, y, Count.減);
        }
        if (rdo乘.isSelected()) {
            sum = 四則運算(x, y, Count.乘);
        }
        if (rdo除.isSelected()) {
            sum = 四則運算(x, y, Count.除);
        }

        lbl答案.setText(String.valueOf(sum));
    }//GEN-LAST:event_btn等於ActionPerformed

    private void txt數字1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt數字1ActionPerformed
        txt數字2.requestFocus();
    }//GEN-LAST:event_txt數字1ActionPerformed

    private void 加減乘除共用事件(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_加減乘除共用事件
        //1.
        // btn等於ActionPerformed(evt);
        //2.
        JRadioButton tmp = (JRadioButton) evt.getSource();
        
         int x, y;
        int sum = 0;
        x = Integer.parseInt(txt數字1.getText());
        y = Integer.parseInt(txt數字2.getText());

        if (tmp==rdo加) {
            sum = 四則運算(x, y, Count.加);
        }
        if (tmp==rdo減) {
            sum = 四則運算(x, y, Count.減);
        }
        if (tmp==rdo乘) {
            sum = 四則運算(x, y, Count.乘);
        }
        if (tmp==rdo除) {
            sum = 四則運算(x, y, Count.除);
        }

        lbl答案.setText(String.valueOf(sum));
        
        

    }//GEN-LAST:event_加減乘除共用事件
    public static int 四則運算(int x, int y, Count op) {

        switch (op) {
            case 加:
                return x + y;
            case 減:
                return x - y;
            case 乘:
                return x * y;
            case 除:
                return x / y;
            default:
                return 0;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window03().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn檢核;
    private javax.swing.JButton btn等於;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl分數等級;
    private javax.swing.JLabel lbl答案;
    private javax.swing.JLabel lbl通過;
    private javax.swing.JRadioButton rdo乘;
    private javax.swing.JRadioButton rdo加;
    private javax.swing.JRadioButton rdo減;
    private javax.swing.JRadioButton rdo除;
    private javax.swing.JTextField txt使用者;
    private javax.swing.JTextField txt分數;
    private javax.swing.JTextField txt密碼;
    private javax.swing.JTextField txt數字1;
    private javax.swing.JTextField txt數字2;
    // End of variables declaration//GEN-END:variables
}
