package source;

import p15.Test15;

public class Main {

    public static void main(String[] args) {

        // Test01.呼叫程式();
        // Test01.參數傳遞();
        //Test01.副程式的種類();
        // Test01.結構化程式1();
        // Test01.結構化程式2();
        // Test01.結構化程式3();
        //   Test01.結構化程式4();
        //  Test01.傳統程式();
        //Test01.物件導向程式1();
        //Test01.物件導向程式2();
        // Test01.由類別產生物件1();
        // Test02.兩數交換();
        //Test02.基本型態();
        // Test02.其他類別_系統提供();
        // Test02.其他類別_使用者自訂();
        // Test02.列舉型別();
        // Test02.變數分類三();
        // Test02.數字表示法();
        // Test02.修飾字();
        //Test02.基本轉基本_轉型();
        //Test02.Scanner2();
        // Test02.輸入框2();
        // Test03.算數1();
        //  Test03.換錢1();
        // Test03.輸入();
        // Test03.算術指派3();
        //Test03.遞增遞減運算子5();
        //Test03.比較3();
        // Test03.邏輯2();
        //Test03.位元();
        //Test03. 三元運算子();
        // Test03.流程3();
        // Test03.輸入帳號密碼1();
        // Test03.if分數等級3();
        // Test03.switch4();
        // Test03.switch分數等級();
        //  Test03.switch站別();
        // Test03.switch三元運算子();
        //Test03.算術運算1();
        // Test03.loop7();
        //   Test03.輸入_loop();
        // Test03.九九乘法1();
        // Test03.九九乘法2();
        // Test03.處理例外();
        //  Test03.寫檔案();
        // Test03.讀檔案();
        //Test03.寫檔案_九九乘法();
        //Test03.讀檔案_九九乘法();
        //Test03.主();
// Test03.break1();
//Test03.continue1();
//Test03.switch分數等級_loop();
//Test03.輸入帳號密碼2();
//Test03.迴圈變形();
//Test03.換錢2();
//Test03.亂數();
//Test03.firstWeekDayOfYear(1);
//Test04.二維空陣列();
//Test04.二維有初始值陣列();
//Test04.函數產生陣列3();
//Test04.快捷迴圈();
//Test04.陣列的比較();
        //  Test04.泡沫排序法();
        // Test04.字串長度();
        //  Test04.取出子字串();
        //  Test05.接力賽();
//Test05.import的用法();
//Test05.連接資料庫_程式設計師1();
        //   Test05.類別之間的關係();
        //  Test05.由類別產生物件4();
        // Test05.物件的內容();
        // Test05.繼承1();
        // Test06.使用Account1();
        //  Test07.加1_傳值();
        // Test07.加1_傳址();
        // Test07.傳址_變數();
        //  Test07.傳址_參數();
//  Test07.傳址_不同的變數();
//Test07.傳址_多型1();
//Test07.傳址_多型2();
        // Test07.回傳1();
        // Test07.傳陣列_一維();
        // Test07.接收陣列_一維();
        // Test07.傳字串2();
        //Test08.建構子多載();
        //  Test08.建構子4();
//  Test09.除以0的例外();
//       Test09.超出陣列索引的例外();
//       Test09.超出字串索引的例外();
//       Test09.空指標的例外();
//       Test09.格式錯的例外();
        //  Test09.多型的例外();
//         Test09.呼叫除以0的例外_自行處理();
        // Test09.呼叫除以0的例外_丟出去();
        // Test09.呼叫除以0的例外_丟出去2();
        //Test09.checked1();
        // Test09.checked1();
        // Test09.checked2();
        //Test09.系統引發1();
        // Test09.自行引發1();
        // Test09.自行處理的例外3();
        // Test09.系統API丟出的例外();
        // Test09.呼叫sumxy();
        // Test09.處理例外訊息的方法();
        //  Test11.多載();
        //  Test11.參數串1();
        //Test11.指派1();
        // Test11.覆蓋();
        //Test11.多型1();
        //Test11.多型2();
        //Test11.多型應用_動態繫結1();
        //  Test11.多型應用_動態繫結2();
        //Test11.多型應用3();
        //   Test11.多型注意1();
//        Test11.多型注意2();
//        Test11.多型注意3();
//        Test11.多型compiler_錯();
//
//        Test11.多型run不同型態轉換_當();
//        Test11.多型run向下轉型_當();
//        Test11.多型run向下轉型_ok();
//        Test11.多型run向上轉型_ok();
//        Test11.主人與客人2();
        //  Test12.匿名巢狀類別轉變5();
        //Test12.匿名巢狀類別_轉換前1();
        // Test12.匿名巢狀類別_轉換前2();
        // Test12.巢狀類別範例1();
        //        Test13.主執行緒();
//     Test13.產生執行緒_繼承();
        // Test13.產生執行緒_實作();
//        Test13.產生執行緒_區域巢狀類別_繼承();
//        Test13.產生執行緒_區域巢狀類別_實作();
//        Test13.產生執行緒_匿名類別_繼承();
//        Test13.產生執行緒_匿名類別_實作1();
//        Test13.產生執行緒_匿名類別_實作2();
//      Test13.產生執行緒_匿名類別_實作3();
//      Test13.join練習();
//       Test13.yield練習();
        //   Test13.共用程式不共用資料();
        //    Test13.共用程式共用資料();
        //      Test13.共用程式共用資料_同步化區塊();
//       Test13.共用程式共用資料_同步化方法();
//        Test13.共用程式不共用資料_同步化方法();
        //   Test13.生產者與消費者();
//       Test13.階乘();      
        // Test13.費式數列();
        //   Test14.使用Object_型態轉換不正確_當掉();
        //Test14.泛型應用_特定物件容器();
        // Test15.陣列();
        // Test15.集合();
        //Test15.Queue集合2();
        //  Test15.Stack集合2();
//Test15.iterator1();
        //      Test15.iterator3();
        //  Test15.Arrays_陣列放到集合();
        //Test15.Collections_洗牌();
        //Test15.字串可以排序_有實作Comparable();
        // Test15.自訂的類別無法排序_沒有實作Comparable();
// Test15.自訂的類別_可以排序有實作Comparable與Comparator_陣列_沒有泛型();
//Test15.字串_hashCode的值();
//Test15.八個包裝類別_加到HashSet集合();
//Test15.字串_加到HashSet集合();
//Test15.自訂類別_沒有覆寫equals與hashCode_加到HashSet集合();
//Test15.自訂類別_有覆寫equals與hashCode_加到HashSet集合();
//Test15.覆寫hashCode的演算法();
//Test15.自訂類別_沒有覆寫hashCode_加到Map();
//Test15.自訂類別_有覆寫hashCode_加到Map();
//Test15.自訂類別_有實作comparable();
        Test15.自訂類別_有覆寫equals跟hashCode();
    }
}
